language: python

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4
    # This is just for "egg_info".  All other builds are explicitly given in the matrix
env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - NUMPY_VERSION=1.9
        - ASTROPY_VERSION=stable
        - CONDA_INSTALL='conda install'
        - PIP_INSTALL='pip install'
        - CONDA_DEPENDENCIES='Cython'
        - PIP_DEPENDENCIES='pytest-xdist'
        - CONDA_OPTIONAL='scipy scikit-image matplotlib'

    matrix:
        - SETUP_CMD='egg_info'

matrix:
    include:

        # Do a coverage test in Python 2. This requires the latest
        # development version of Astropy, which fixes some issues with
        # coverage testing in affiliated packages.
        - python: 2.7
          env: ASTROPY_VERSION=development SETUP_CMD='test --coverage'

        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time
        - python: 2.7
          env: ASTROPY_VERSION=development SETUP_CMD='build_sphinx -w'
        - python: 3.4
          env: ASTROPY_VERSION=development SETUP_CMD='build_sphinx -w'

        # Try Astropy development version
        - python: 3.3
          env: ASTROPY_VERSION=development SETUP_CMD='test'

        # Try all python versions with the latest numpy
        - python: 2.6
          env: SETUP_CMD='test'
        - python: 2.7
          env: SETUP_CMD='test'
        - python: 3.3
          env: SETUP_CMD='test'
        - python: 3.4
          env: SETUP_CMD='test'

        # Try with optional dependencies disabled
        - python: 2.7
          env: SETUP_CMD='test' CONDA_DEPENDENCIES+=$CONDA_OPTIONAL
        - python: 3.4
          env: SETUP_CMD='test' CONDA_DEPENDENCIES+=$CONDA_OPTIONAL

        # Try older numpy versions
        - python: 2.7
          env: NUMPY_VERSION=1.8 SETUP_CMD='test'
        - python: 2.7
          env: NUMPY_VERSION=1.7 SETUP_CMD='test'
        - python: 2.7
          env: NUMPY_VERSION=1.6 SETUP_CMD='test'

before_install:

    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

    # Make sure that interactive matplotlib backends work
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

script:
   - python setup.py $SETUP_CMD

after_success:
    - if [[ $SETUP_CMD == 'test --coverage' ]]; then coveralls --rcfile='photutils/tests/coveragerc'; fi
